# Generated by Django 4.2.4 on 2023-08-13 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cobrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contribuyente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('codigo', models.IntegerField(blank=True, null=True)),
                ('N_cedula', models.CharField(blank=True, max_length=255, null=True)),
                ('Comunidad', models.CharField(blank=True, max_length=60)),
                ('Direccion', models.TextField(blank=True, max_length=100)),
                ('data_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField()),
                ('register_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Base_register.cobrador')),
            ],
        ),
        migrations.CreateModel(
            name='CuentasPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(blank=True, max_length=50)),
                ('code_max', models.CharField(max_length=18)),
                ('min_code', models.CharField(max_length=6)),
                ('p_year', models.BooleanField(default=False, help_text='este campo solo se aplica en pagos anuales')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_empresa', models.CharField(max_length=255)),
                ('Direcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Months',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enero', models.BooleanField(default=False)),
                ('feb', models.BooleanField(default=False)),
                ('mar', models.BooleanField(default=False)),
                ('abril', models.BooleanField(default=False)),
                ('may', models.BooleanField(default=False)),
                ('Juni', models.BooleanField(default=False)),
                ('Juli', models.BooleanField(default=False)),
                ('Agos', models.BooleanField(default=False)),
                ('Sep', models.BooleanField(default=False)),
                ('Octu', models.BooleanField(default=False)),
                ('Nov', models.BooleanField(default=False)),
                ('Dic', models.BooleanField(default=False)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base_register.contribuyente')),
            ],
        ),
        migrations.CreateModel(
            name='Years',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateMonthsContry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_at', models.DateField(auto_now_add=True)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base_register.months')),
            ],
        ),
        migrations.CreateModel(
            name='PagoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, max_length=3)),
                ('activo', models.BooleanField(default=True)),
                ('data_at', models.DateField(auto_now_add=True)),
                ('contribuyente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Base_register.contribuyente')),
                ('cuenta_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Base_register.cuentaspagos')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Base_register.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Ordering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_abs', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('CH', 'CH'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=2)),
                ('primer_apellido', models.CharField(blank=True, max_length=100)),
                ('complete_name', models.IntegerField(blank=True, null=True)),
                ('id_type_abs', models.IntegerField()),
                ('id_primer_apellido', models.IntegerField()),
                ('id_complete_name', models.IntegerField()),
                ('contryUnique', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Base_register.contribuyente')),
            ],
        ),
        migrations.AddField(
            model_name='months',
            name='years',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base_register.years'),
        ),
    ]
